In [1]:
import numpy  as np;

In [2]:
x=np.diag((1,2,3));

In [3]:
x


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [4]:
a,b=np.linalg.eig(x)

In [6]:
a

array([ 1.,  2.,  3.])

In [7]:
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
for i in range(3):
    if (np.dot(x,b[:][i])==a[i]*b[:][i]).all():
        print('正确');
    else:print('错误');

正确
正确
正确
